MAIN=main.cpp

OBJECTS=$(MAIN:.cpp=.o)

CC=g++

CFLAGS=-c -Wall



all: $(MAIN)
	$(CC) $(MAIN) -o main

main.o: main.cpp
	$(CC) $(CFLAGS) main.cpp

data.o: data.h
	$(CC) $(CFLAGS) tingpt/data.cpp

model.o: model.h
	$(CC) $(CFLAGS) tingpt/model.cpp

train.o: train.cpp
	$(CC) $(CFLAGS) tingpt/train.cpp

clean:
	rm -rf *.o main

